# Generated by Django 5.0.6 on 2025-01-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=800)),
                ('address', models.CharField(max_length=10000)),
                ('contact_number', models.CharField(max_length=800)),
                ('email', models.CharField(max_length=800)),
                ('website', models.CharField(max_length=800)),
            ],
        ),
    ]
